name = "han-analytics"
compatibility_date = "2024-10-12"
pages_build_output_dir = "dist"

[[analytics_engine_datasets]]
binding = "AnalyticsBinding"
dataset = "AnalyticsDataset"
[vars]
CLOUDFLARE_ACCOUNT_ID = 'f775e74e879913699b1444225fdcf589'
CLOUDFLARE_API_TOKEN = '_QUIJRUEfmQTnwTrgdFeQXKjwU4_yMpehIjDQc7S'
# 网站访问密码 (不设置即无需密码访问)
CLOUDFLARE_WEBSITE_PWD = 'aehyok1012'
# 可统计的白名单 格式：  域名,WebSite|域名,WebSite，多个站点使用|分隔 例如：'api.vvhan.com,Hello-Han-Api|www.vvhan.com,Hello-HanHexoBlog'  (不设置即允许任何统计)
CLOUDFLARE_WEBSITE_WHITELIST = 'www.aehyok.uk,blog|han.aehyok.uk,han'
